---
require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Rails:
  Enabled: true

Layout/LineLength:
  Max: 125

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

RSpec/ExampleLength:
  Max: 10

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
